---
title: "day 4 comp loop and function practice"
author: "Connor Flynn"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(palmerpenguins)
library(tidyverse)
```

```{r}
quarter_split <- c(1.0, 1.1, 1.2, 1.1, 1.4, 1.5, 1.6, 1.4)

half_splits <- vector(mode = "numeric", length =
                  length(quarter_split) - 1)
            


for (i in seq_along(quarter_split) - 1) {
  half_mile <- quarter_split[i] + quarter_split[i + 1]
  half_splits[i] <- half_mile
}


half_splits
```


##Writing Functions

```{r}
birddog_sum <- function(bird, dog) {
  add_birddog <- bird + dog
  return(add_birddog)
}

bird100_dog5 <- birddog_sum(bird = 100, dog = 5)

```


```{r}
say_hello <- function(friend, weekday) {
  print(paste("hello", friend, "have a great", weekday))
}

say_hello(friend = "Connor", weekday = "Thursday")

```


```{r}
find_multiple <- function(a, b) {
  my_multiplication <- a * b
  print(my_multiplication)
}
  
  
  
final_value1 <- find_multiple(a = 10, b = 6) 
  
```

```{r}
animal_age <- function(animal, age) {
  
  if (!animal %in% c("dog", "goat", "bear")) {
    warning("animal must be a dog, goat or bear")
  }
  
  if (animal == "dog") {
    creature_age <- age * 7
  }
  else if (animal == "goat") {
    creature_age <- age * 8
  }
  else if (animal == "bear") {
    creature_age <- age * 12
  }
  return(creature_age)
  }

animal_age(animal = "bear", age = 5)

```

```{r}
adelie_gentoo <- penguins %>% 
  filter(species %in% c("Adelie", "Gentoo"))


## %in% replaces == because == looks for 
## does row 1 match Adelie, does row 2 match Gentoo
## does row 3 match Adelie, does row 4 match Gentoo
## %in% says does row 1 match Adelie or Gentoo, 
## does row 2 match Adelie or Gentoo

```


```{r}
### Combine functions and for loops


df_means <- function(df) {
  for (i in 1:ncol(df)) {
    col_mean <- mean(df[[i]])
    column_name <- colnames(df[i])
    print(paste("The mean of", column_name, "is",
    col_mean))
  }
}



```


```{r}
## Make a subset of only structural size variables from
## the penguins dataset for Chinstrap
## filter is for rows, select is for columns

chinstrap_sizes <- penguins %>% 
  filter(species == "Chinstrap") %>%
  select(species, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)

df_means(df = chinstrap_sizes)

```

```{r}
## Condition to check class of an input

lunchtime <- function(tacos, price_per) {
  tot_price <- tacos * price_per
  return(tot_price)
}

lunchtime(tacos = 4, price_per = 2)

```

```{r}
## Use values form a dataframe to calculate something based on user input


# Calculate the groundwater transport rate

gw_rate <- function(site) {
  gw_slope_depth <- data.frame(sitename = c("mountain", "prairie", "desert",
  "beach"), 
  depth = c(32, 41, 63, 2), 
  slope = c(11.2, 0.4, 0.8, 2.6))
  site_select <- filter(gw_slope_depth, sitename == site)
  transport_rate <- 1.4 * site_select$slope + 3.6 * site_select$depth
  return(transport_rate)
}

gw_rate(site = "beach")

```
```{r}
## Same thing as above using switch

gw_rate_switch <- function(site) {
  gw_slope_depth <- switch(site, 
                           "mountain" = c(32, 11.2),
                           "prairie" = c(41, 0.4),
                           "desert" = c(63, 0.8),
                           "beach" = c(2, 2.6))
  transport_rate <- 1.4 * gw_slope_depth[2] + 3.6 *gw_slope_depth[1]
  return(transport_rate)
}

gw_rate_switch(site = "beach")
```


```{r}
## Logistic growth equation
# Write right side of equation than click ctr alt x to put into function format

logistic_growth <- function(K, N0, r, time) {
  Nt <- K / (1 + ((K - N0) / N0) * exp(-r * time))
  print(Nt)
}

logistic_growth(K =500, N0 =200, r = 0.43, time = 6)

time_vec <- seq(from = 0, to = 35, by =0.1)
bacterial_growth <- logistic_growth(K = 500, N0 = 200, r = 0.43, time = time_vec)

bacterial_df <- data.frame(time_vec, bacterial_growth)

ggplot(data = bacterial_df, aes(x = time_vec, y = bacterial_growth)) +
  geom_point()

```

```{r}
r_seq <- seq(from = 0.20, to = 0.40, by = 0.01)
time_vec <- seq(from = 0, to = 35, by =0.1)

out_matrix <- matrix(ncol = length(r_seq), nrow = length(time_vec))

# N0 = 100, K = 6000

for (i in seq_along(r_seq)) {
  for (j in seq_along(time_vec)) {
    pop <- logistic_growth(K = 6000, N0 = 100, r = r_seq[i], time = time_vec[j])
    out_matrix[j, i] <- pop
  }
}

# Wrangling

out_df <- data.frame(time = time_vec, out_matrix)


# Update column names

colnames(out_df) <- c("time", paste0("gr_", r_seq))

# make a long form (tidy version) of data

out_df_long <- out_df %>% 
  pivot_longer(-time, names_to = "growth_rate", values_to = "population")

# Make in ggplot a line graph geom_line for population y axis over time x axis
# with color depending on the growth rate

ggplot(data = out_df_long, aes(x = time, y = population)) + 
  geom_line(aes(color = growth_rate))


```

